### ISSUE TITLE
in the new version, it appears that switching branches doesn't switch files

### ISSUE THREAD

**Issue by ophiry** [dataversioncontrol/dvc#277]
```
dvc run cp ~/foo d1/file
# file is now foo
git checkout -b branch
dvc run cp ~/bar d1/file
# file is now bar
git checkout -
# file is still bar, but should be foo
```

**Comment by efiop** [comment]
Hi @ophiry !

Are you running most recent master? If so, dvc now uses hardlinks instead of symlinks, so you need to run 'dvc checkout' after 'git checkout', so dvc can setup data files properly.

We are trying to add all of the backward-incompatible changes now, so we can stabilize dvc configs and other repo files for the next release.

**Comment by ophiry** [comment]
still doesn't work:
```
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (master)> dvc run cp ~/foo d1/file2                                                23:32:01
File cp from argv is outside of git directory and cannot be traced
File d1/file2 from argv is outside of git directory and cannot be traced
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (master)> cat d1/file2                                                             23:33:14
foo
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (master)> git checkout -b branch4                                                  23:33:19
Switched to a new branch 'branch4'
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (branch4)> dvc checkout                                                            23:33:28
Checkout 'd1/file2'
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (branch4)> dvc run cp ~/bar d1/file2                                               23:33:37
File cp from argv is outside of git directory and cannot be traced
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (branch4)> cat d1/file2                                                            23:33:56
bar
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (branch4)> git checkout -                                                          23:34:01
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (master)> dvc checkout                                                             23:34:09
(dvc) ophir@Ophirs-MacBook-Pro ~/d/binaries (master)> cat d1/file2                                                             23:34:18
bar
```

also, seem somewhat error prone in case a user forget `dvc checkout`, not sure what are the other considerations, but the fact that the symlinks change automatically with the checkout was a powerful feature

**Comment by dmpetrov** [comment]
@ophiry just to make it clear. To minimize the number of releases with breaking changes we've decided to incorporate all breaking changes from the roadmap into the current release. One of these changes is hard links instead of symlinks and getting rid of mandatory `data` dir.

With hard links DVC API\commands line will change a bit. Today is not 100% clear how exactly it will change. For example, we might have an additional `dvc checkout` command or we might add DVC logic to the regular `git checkout` as a hook. Your opinions and feedback are highly appreciated.

The current code in the `master` branch will not be stable for a while. I'm sure we will stabilize the codebase in a couple weeks.

**Comment by efiop** [comment]
Found the bug in repo_change. Will fix ASAP. Thanks for reporting!

**Comment by ophiry** [comment]
Did some testing with the new version, and I believe the issue still exists.
If you checkout a branch, but forget to do dvc checkout you end up with the previous file without a simple method to discover the issue

**Comment by efiop** [comment]
Hi @ophiry !

We've discussed adding a command for installing git hooks in #657 and it should be ready for 0.9.7. For now, as a workaround, you can add `dvc checkout` to your post-checkout git hook yourself.
