### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by matanster** [dataversioncontrol/dvc#364]
Hi,

Is it possible to store data locally rather on AWS or Google Cloud?
Also, do you have any instructions for building from the source, if it's not too early?

Thanks!

**Comment by dmpetrov** [comment]
Hi @matanster 
Yes, by default DVC stores data only in local caches. Syncing the cache to cloud is a separate feature which you do not need to use.

However, due to a bug in the current version, you have to have the AWS credentials file. The file can be empty. Empty `~/.aws/credentials` file example:

```
[default]
aws_access_key_id = 
aws_secret_access_key = 
```

The new DVC version is under active development. I don't recommend to use `master` branch right now. Please use the released version through `pip install dvc` or `pip3 install dvc`.

**Comment by matanster** [comment]
@dmpetrov thanks a lot. Maybe a small idea would be to add an explicit note in the readme about not _requiring_ cloud? anyway thanks for the workaround :-) Do you have any suggestion on how to think about changes to a workflow? is there any dvc command for changing a flow?

**Comment by dmpetrov** [comment]
"not requiring cloud" tag - is a good idea. I heard this kind of concern from a couple people. But DVC was initially designed as a local tool where the cloud integration is an "inevitable evil".

In the current release version, data file recreation works the best: `dvc remove data/output.p && dvc run python myscript.py data/input.scv data/output.p`
The upcoming version is more flexible from the workflow modification point of view. But it is under development.
