### ISSUE TITLE
Reproducible target files (*.dvc) consistent locations

### ISSUE THREAD

**Issue by villasv** [dataversioncontrol/dvc#611]
I've noticed that issuing `dvc add data/file.csv` will create a `data/file.csv.dvc`, but running free commands like `dvc run -d data/file.csv -o data/out.csv python whatever.py` will create the `out.csv.dvc` in the project root directory.

Why not keep those *.dvc files hidden inside the `.dvc` folder? So running `dvc repro file.csv` could be the equivalent of currently running `dvc repro .dvc/file.csv.dvc`.

Or, if we don't want to go that far, at least keep it consistent and write `out.csv.dvc` into `data/` as well.

**Comment by villasv** [comment]
Hmm. It's truly something to think over. Exactly because the default file name would be `out.csv.dvc` I was inclined to associate that file with "how to reproduce file `out.csv`", and thus it made sense to be together with `out.csv` inside `data/`.

On the other hand, it really should be interpreted as "how to reproduce the command that generated `out.csv`", so really `whatever.dvc` is a better name, and it makes sense to not be inside `data/` (perhaps in the root as is or inside `code/`). When having multiple output files for example, this is even more evident.

So what I could do is to `cd` into `code/` and run `dvc run -f whatever.dvc d data/file.csv -o data/out.csv python whatever.py`, and `whatever.dvc` would be inside `code/` and would have a more intuitive name.

Would that be "ok" (not "meeh ok" as in shoving those *.dvc inside `.dvc`, but as in good practices "ok")? Or should I just wrap my head around keeping those *.dvc files in the root folder?

**Comment by efiop** [comment]
> Hmm. It's truly something to think over. Exactly because the default file name would be out.csv.dvc I was inclined to associate that file with "how to reproduce file out.csv", and thus it made sense to be together with out.csv inside data/.

I agree that it is a bit confusing, but `dvc run` just chooses first output and slaps ".dvc" to it, if you don't specify the name of the dvc file yourself. It used to default to "Dvcfile", but it was overwriting itself if you run two commands, this is why we chose to just use first output name + .dvc by default. Feel free to share your thoughts on the naming scheme.

> So what I could do is to cd into code/ and run dvc run -f whatever.dvc d data/file.csv -o data/out.csv python whatever.py, and whatever.dvc would be inside code/ and would have a more intuitive name.

Or you could use `--cwd code/ --file whatever.dvc`, so dvc will `cd` for you. Just make sure that `whatever.py` is aware of the location it is going to be run from.

> Would that be "ok" (not "meeh ok" as in shoving those *.dvc inside .dvc, but as in good practices "ok")? Or should I just wrap my head around keeping those *.dvc files in the root folder?

Ah, sorry, i explained "recommended/not recommended" poorly. So we don't advocate for storing all dvcfiles in the root, not at all. We don't have a set of "good practices" just yet, we just really want projects to be organized neatly. From my previous comment you might get an impression that I am not recommending putting your files under directories at all, but that is not what I meant. What I meant is that I don't think that hiding your files out of site at all(i.e. under .dvc or some other "invisible" location) is a good thing to do. I'm perfectly fine with reasonable locations for *.dvc files and your example with storing `whatever.dvc` under `code/` makes perfect sense to me and I would definitely consider it a good practice. :smiley: One more thing that would greatly improve the structure of the project is adding Dvcfile to the root, that will point to the default output, so that you can use `dvc repro` in your project's root and have it build the default target. E.g.:
```
dvc add data/file.csv
dvc run -f whatever.dvc -c code/ -d ../data/file.csv -o ../data/out.csv python whatever.py
dvc run -f Dvcfile -d data/out.csv
dvc repro
```

**Comment by efiop** [comment]
Btw, that trick with 'Dvcfile' from my previous comment also suggests another way to structure your project. I.e. lets say we have N stages(N=2 for simplicity): foo and bar.  So we could organize our project this way:
```
mkdir foo
cd foo
echo 'input' > input
echo 'some foo code' > run.py
dvc run -d input -o output python run.py
cd ..

mkdir bar
echo 'some bar code' > run.py
dvc run -d ../foo/input -o output python run.py
cd ..

dvc run -f Dvcfile -d bar/output
```

This way you've created your pipeline of two stages, and you can `cd` to any of the stages and run `dvc repro` to reproduce this particular stage(and it's dependecies) and you could also run `dvc repro` from the root dir, reproducing the whole pipeline.

As I said, we don't have like an established "good practices" list just yet, only a few tips and tricks, so we would really appreciate the feedback and any input.

**Comment by villasv** [comment]
Oh, yeah. That reminds me of that talk on Principled Data Science by Patrick Ball that basically set up that flow with a bunch of symlinks and enormous Makefiles. For now I'll stick to the simple approach with just `code/` and `data/` folders, but I see how this last suggestion could benefit projects with very complex steps.

I'll close the issue, it went from feature request to question solved ;)
