### ISSUE TITLE
dvc files are scattered across codebase

### ISSUE THREAD

**Issue by rahulguptajss** [dataversioncontrol/dvc#635]
Hi,

Is it possible to keep all .dvc files in same folder. Currently my project structure gets complicated due to several dvc files across folders. Specially when root folder has multiple dvc files. This can easily turn into maintenance hazard as project grows or someone mistakenly deletes as dvc file. I believe dvc files should be limited to a single folder. It could be similar to .dvc/.git folder.

Regards,
Rahul

**Comment by efiop** [comment]
@rahulguptajss It is possible, please see #611 referenced by @villasv ,we've discussed this topic there in-depth.

**Comment by rahulguptajss** [comment]
Thanks we can close this.

**Comment by rahulguptajss** [comment]
dvc add doesn't support -f option. If i am adding an input file under dvc tracking then dvc file gets created in that directory only.

**Comment by efiop** [comment]
Yes, `-f` and `-c` options are not supported by `dvc add`. I believe you can workaround it by using `dvc run -o file`.

**Comment by rahulguptajss** [comment]
Thanks that would work. I have updated my comment above to include another issue.

**Comment by efiop** [comment]
@rahulguptajss You should use `-c` option there as well. I.e. your command should be `dvc run -d ../data/CombinedSummary.csv -d ../source/scripts/split_train_test.py -o ../data/train.p -c dvc -f split_train_test.dvc python ../source/scripts/split_train_test.py` This is because your command should be running from the same directory that dvc file is located in.

**Comment by rahulguptajss** [comment]
Thanks this works. :-)
