### ISSUE TITLE
Handle dvc init when git repository is not initialized

### ISSUE THREAD

**Issue by prihoda** [dataversioncontrol/dvc#660]
When running `dvc init` before `git init`, the following error is shown:

_Unexpected error: 'Base' object has no attribute 'GITIGNORE'_

The `.dvc` folder is created but no `.gitignore` file is added. Running `dvc init` again fails.

I guess best solution would be to exit without creating any files when the git repository is not initialized?

**Comment by efiop** [comment]
Hi @prihoda !

dvc actually supposed to run even without git. The only difference for `dvc init` would be that it would not create .gitignore and will not add the changes to git. Other than that, dvc should be operational even without git. I think that we should add `--bare` or `--no-scm` option for `dvc init` so that we can be sure that user actually wants to initiate dvc repo in a plain directory. Created #662 for that.

The error you are experiencing here is definitely a bug. Will prepare a patch ASAP.

Thank you for the feedback!
