### ISSUE TITLE
1 GCS bucket for multiple dvc controlled repos

### ISSUE THREAD

**Issue by zacharymostowsky** [dataversioncontrol/dvc#691]
HI, I was wondering if it was acceptable to use 1 GCS bucket to handle storage for multipe dvc controlled repos. There shouldn't be any clashing of file names, correct?

Thanks,
Zach

**Comment by efiop** [comment]
Hi @zacharymostowsky !

Great question! Currently cache files are identified with the path that is essentially a md5 sum of that file, so the possibility of the filenames clashing is very low. That being said, so far dvc wasn't developed with that scenario in mind, so I can't say that we can recommend storing your projects' cache like that. Could you please shed some light on why would you want to dump all of your projects' cache into a single directory instead of using unique ones?

Thanks,
Ruslan

**Comment by zacharymostowsky** [comment]
I have a several projects that fall under the same category. But, yes, I agree nesting the storage in a subfolder of the bucket is most likely better. Thanks. I am going to close this.

Zach
