### ISSUE TITLE
Aws setup error

### ISSUE THREAD

**Issue by mfrata** [dataversioncontrol/dvc#727]
When i do a `dvc status` or `dvc push` i receive this error:

`Initialization error: Config file error: Key 'aws' error:
Wrong keys 'credentialsection' in {'storagepath': '<my_bucket_name>/dvc/svm', 'credentialpath': '/home/mfrata/.aws/credentials', 'credentialsection': 'default'}`

My `.dvc/config` file is like this:
```
[Global]
Cloud = aws
[AWS]
StoragePath = <my_bucket_name>/dvc/svm
CredentialPath = /home/mfrata/.aws/credentials
CredentialSection = default
```
So i did these commands like the [docs](https://dataversioncontrol.com/docs#configuration_cloud). But it's not working.

**Comment by efiop** [comment]
Hi @mfrata !

'CredentialSection' is actually an obsoleted and not supported. Renaming it to 'Profile' should make it work.

The docs are actually a bit outdated, we are currently working on updating them.
The modern(and recommended) approach to this would consist of two commands in your case:
```
$ dvc remote add myremote s3://<my_bucket_name>/dvc/svm
$ dvc config core.remote myremote
```
because you are using default profile and credpath.

Thanks,
Ruslan

**Comment by villasv** [comment]
Also remember to substitute `<my_bucket_name>` for your desired bucket name.

**Comment by mfrata** [comment]
It worked!!
![image](https://user-images.githubusercontent.com/15002208/40432496-3862bd70-5e80-11e8-9f1e-bda2def4eee5.png)

Renaming `CredentialSection` to `Profile` didn't worked, but those two magic commands did.

Thank you @efiop and @villasv for the answers.
